In [1]:
import pandas as pd

In [2]:
hotmaps = pd.read_csv('../Data/building_stock.csv', sep= "|")

In [3]:
hotmaps

,country,country_code,sector,subsector,btype,bage,topic,feature,type,detail,estimated,value,unit,source
0,Austria,at,Residential sector,Residential sector,Total,NaN,BUILDING,Area,Constructed area [Mm²],NaN,0,347.351953,Mm²,NaN
1,Austria,at,Residential sector,Residential sector,Total,NaN,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,5.750000,1e6 dimensionless,NaN
2,Austria,at,Residential sector,Residential sector,Total,NaN,BUILDING,Area,Number of buildings [Mil.],NaN,0,3.373900,1e6 dimensionless,NaN
3,Austria,at,Residential sector,Residential sector,Total,NaN,BUILDING,Tenure/ownership status and distribution,Owner occupied - dwellings/units [Mil.],NaN,0,3.289000,1e6 dimensionless,NaN
4,Austria,at,Residential sector,Residential sector,Total,NaN,BUILDING,Tenure/ownership status and distribution,Private rented - dwellings/units [Mil.],NaN,0,1.564000,1e6 dimensionless,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63806,EU27+UK,eu27+UK,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Final energy consumption,Domestic hot water [kWh/m² year],NaN,0,6.704672,kWh/m²/year,NaN
63807,EU27+UK,eu27+UK,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total useful energy demand,Space heating+Domestic hot water [TWh/year],NaN,0,10.753914,TWh/year,NaN
63808,EU27+UK,eu27+UK,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total useful energy demand,Space cooling [TWh/year],NaN,0,3.733398,TWh/year,NaN
63809,EU27+UK,eu27+UK,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total final energy consumption,Space heating+Domestic hot water [TWh/year],NaN,0,14.180832,TWh/year,NaN
63810,EU27+UK,eu27+UK,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total final energy consumption,Space cooling [TWh/year],NaN,0,1.241680,TWh/year,NaN

In [4]:
hotmaps_uk = hotmaps[hotmaps['country'] == 'United Kingdom']

In [5]:
hotmaps_uk

,country,country_code,sector,subsector,btype,bage,topic,feature,type,detail,estimated,value,unit,source
58408,United Kingdom,uk,Residential sector,Total,Total,NaN,BUILDING,Area,Constructed area [Mm²],NaN,0,2215.019495,Mm²,NaN
58409,United Kingdom,uk,Residential sector,Total,Total,NaN,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,30.388568,1e6 dimensionless,NaN
58410,United Kingdom,uk,Residential sector,Total,Total,NaN,BUILDING,Area,Number of buildings [Mil.],NaN,0,17.630000,1e6 dimensionless,NaN
58411,United Kingdom,uk,Residential sector,Total,Total,NaN,BUILDING,Tenure/ownership status and distribution,Owner occupied - dwellings/units [Mil.],NaN,0,19.691792,1e6 dimensionless,NaN
58412,United Kingdom,uk,Residential sector,Total,Total,NaN,BUILDING,Tenure/ownership status and distribution,Private rented - dwellings/units [Mil.],NaN,0,5.196445,1e6 dimensionless,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60503,United Kingdom,uk,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Final energy consumption,Domestic hot water [kWh/m² year],NaN,0,9.401912,kWh/m²/year,NaN
60504,United Kingdom,uk,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total useful energy demand,Space heating+Domestic hot water [TWh/year],NaN,0,0.640554,TWh/year,NaN
60505,United Kingdom,uk,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total useful energy demand,Space cooling [TWh/year],NaN,0,0.165805,TWh/year,NaN
60506,United Kingdom,uk,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total final energy consumption,Space heating+Domestic hot water [TWh/year],NaN,0,1.031708,TWh/year,NaN
60507,United Kingdom,uk,Service sector,Other non-residential buildings,Other non-residential buildings,2000 - 2010,ENERGY,Total final energy consumption,Space cooling [TWh/year],NaN,0,0.094509,TWh/year,NaN

In [6]:
hotmaps_uk = hotmaps_uk[(hotmaps_uk['topic'] == 'BUILDING') & (hotmaps_uk['type'] == 'Number of dwellings/units [Mil.]') & (hotmaps_uk['sector'] == 'Residential sector')]

In [7]:
hotmaps_uk

,country,country_code,sector,subsector,btype,bage,topic,feature,type,detail,estimated,value,unit,source
58409,United Kingdom,uk,Residential sector,Total,Total,NaN,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,30.388568,1e6 dimensionless,NaN
58419,United Kingdom,uk,Residential sector,Total,Total,Before 1945,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,9.313831,1e6 dimensionless,NaN
58452,United Kingdom,uk,Residential sector,Total,Total,1945 - 1969,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,5.991272,1e6 dimensionless,NaN
58487,United Kingdom,uk,Residential sector,Total,Total,1970 - 1979,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,2.629445,1e6 dimensionless,NaN
58522,United Kingdom,uk,Residential sector,Total,Total,1980 - 1989,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.893393,1e6 dimensionless,NaN
58557,United Kingdom,uk,Residential sector,Total,Total,1990 - 1999,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.802984,1e6 dimensionless,NaN
58592,United Kingdom,uk,Residential sector,Total,Total,2000 - 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,5.046062,1e6 dimensionless,NaN
58628,United Kingdom,uk,Residential sector,Total,Total,Post 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,3.711580,1e6 dimensionless,NaN
58661,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,NaN,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,23.896521,1e6 dimensionless,NaN
58669,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,Before 1945,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,7.117023,1e6 dimensionless,NaN
58702,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1945 - 1969,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,5.042449,1e6 dimensionless,NaN
58735,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1970 - 1979,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.910041,1e6 dimensionless,NaN
58768,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1980 - 1989,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.382744,1e6 dimensionless,NaN
58801,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1990 - 1999,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.368008,1e6 dimensionless,NaN
58834,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,2000 - 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,3.987522,1e6 dimensionless,NaN
58868,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,Post 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,3.088734,1e6 dimensionless,NaN
58899,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,NaN,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,4.473479,1e6 dimensionless,NaN
58909,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,Before 1945,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.600165,1e6 dimensionless,NaN
58942,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1945 - 1969,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.544601,1e6 dimensionless,NaN
58975,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1970 - 1979,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.538612,1e6 dimensionless,NaN
59008,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1980 - 1989,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.350067,1e6 dimensionless,NaN
59041,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1990 - 1999,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.324230,1e6 dimensionless,NaN
59074,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,2000 - 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.709137,1e6 dimensionless,NaN
59108,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,Post 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.406666,1e6 dimensionless,NaN
59140,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,NaN,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,2.018568,1e6 dimensionless,NaN
59150,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,Before 1945,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.596643,1e6 dimensionless,NaN
59183,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1945 - 1969,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.404222,1e6 dimensionless,NaN
59216,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1970 - 1979,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.180792,1e6 dimensionless,NaN
59249,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1980 - 1989,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.160581,1e6 dimensionless,NaN
59282,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1990 - 1999,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.110746,1e6 dimensionless,NaN
59315,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,2000 - 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.349403,1e6 dimensionless,NaN
59349,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,Post 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.216180,1e6 dimensionless,NaN

In [10]:
hotmaps_at = hotmaps[hotmaps['country'] == 'Austria']
hotmaps_at = hotmaps_at[(hotmaps_at['topic'] == 'BUILDING') & 
                        (hotmaps_at['type'] == 'Number of buildings [Mil.]') & 
                        (hotmaps_at['sector'] == 'Residential sector') & 
                        (hotmaps_at['subsector'] == 'Single family- Terraced houses')]

In [14]:
hotmaps_at.drop(columns=['btype', 'topic', 'feature', 'detail', 'estimated', 'source', 'unit', 'sector'])

,country,country_code,subsector,bage,type,value
281,Austria,at,Single family- Terraced houses,NaN,Number of buildings [Mil.],2.8399
289,Austria,at,Single family- Terraced houses,Before 1945,Number of buildings [Mil.],0.5800
326,Austria,at,Single family- Terraced houses,1945 - 1969,Number of buildings [Mil.],0.7100
360,Austria,at,Single family- Terraced houses,1970 - 1979,Number of buildings [Mil.],0.4800
396,Austria,at,Single family- Terraced houses,1980 - 1989,Number of buildings [Mil.],0.4000
432,Austria,at,Single family- Terraced houses,1990 - 1999,Number of buildings [Mil.],0.4100
468,Austria,at,Single family- Terraced houses,2000 - 2010,Number of buildings [Mil.],0.2100
506,Austria,at,Single family- Terraced houses,Post 2010,Number of buildings [Mil.],0.0499

In [35]:
hotmaps_uk = hotmaps[hotmaps['country'] == 'United Kingdom']
hotmaps_uk['type'].unique()

array(['Constructed area [Mm²]', 'Number of dwellings/units [Mil.]',
       'Number of buildings [Mil.]',
       'Owner occupied - \xa0dwellings/units\xa0 [Mil.]',
       'Private rented \xa0- \xa0dwellings/units [Mil.]',
       'Social housing \xa0- \xa0dwellings/units [Mil.]',
       'Occupied [Mil.]', 'Vacant [Mil.]', 'Heated area [Mm²]',
       'Cooled area [Mm²]',
       'Secondary dwellings/ units and others [Mil.]', 'Walls', 'Windows',
       'Roof', 'Floor', 'brick', 'solid wall', 'wood', 'single glazing',
       'tilted roof', 'concrete', 'concrete slab',
       'Space heating [kWh/m² year]', 'Space cooling [kWh/m² year]',
       'Domestic hot water  [kWh/m² year]',
       'Domestic hot water [kWh/m² year]',
       'Space heating+Domestic hot water [TWh/year]',
       'Space cooling [TWh/year]', 'flat roof', 'cavity wall', nan,
       'double glazing'], dtype=object)

In [37]:
hotmaps_uk = hotmaps[hotmaps['country'] == 'United Kingdom']
hotmaps_uk = hotmaps_uk[(hotmaps_uk['topic'] == 'BUILDING') 
                        & (hotmaps_uk['type'] == 'Number of dwellings/units [Mil.]') 
                        & (hotmaps_uk['subsector'] != 'Total')
                        & (hotmaps_uk['sector'] == 'Residential sector')]

hotmaps_uk = hotmaps_uk.dropna(subset=['bage'])

In [38]:
hotmaps_uk

,country,country_code,sector,subsector,btype,bage,topic,feature,type,detail,estimated,value,unit,source
58669,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,Before 1945,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,7.117023,1e6 dimensionless,NaN
58702,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1945 - 1969,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,5.042449,1e6 dimensionless,NaN
58735,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1970 - 1979,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.910041,1e6 dimensionless,NaN
58768,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1980 - 1989,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.382744,1e6 dimensionless,NaN
58801,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,1990 - 1999,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.368008,1e6 dimensionless,NaN
58834,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,2000 - 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,3.987522,1e6 dimensionless,NaN
58868,United Kingdom,uk,Residential sector,Single family- Terraced houses,Single family- Terraced houses,Post 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,3.088734,1e6 dimensionless,NaN
58909,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,Before 1945,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,1.600165,1e6 dimensionless,NaN
58942,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1945 - 1969,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.544601,1e6 dimensionless,NaN
58975,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1970 - 1979,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.538612,1e6 dimensionless,NaN
59008,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1980 - 1989,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.350067,1e6 dimensionless,NaN
59041,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,1990 - 1999,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.324230,1e6 dimensionless,NaN
59074,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,2000 - 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.709137,1e6 dimensionless,NaN
59108,United Kingdom,uk,Residential sector,Multifamily houses,Multifamily houses,Post 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.406666,1e6 dimensionless,NaN
59150,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,Before 1945,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.596643,1e6 dimensionless,NaN
59183,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1945 - 1969,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.404222,1e6 dimensionless,NaN
59216,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1970 - 1979,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.180792,1e6 dimensionless,NaN
59249,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1980 - 1989,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.160581,1e6 dimensionless,NaN
59282,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,1990 - 1999,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.110746,1e6 dimensionless,NaN
59315,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,2000 - 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.349403,1e6 dimensionless,NaN
59349,United Kingdom,uk,Residential sector,Appartment blocks,Appartment blocks,Post 2010,BUILDING,Area,Number of dwellings/units [Mil.],NaN,0,0.216180,1e6 dimensionless,NaN

In [41]:
for index, row in hotmaps_uk.iterrows():
    country = row['country_code'].upper()
    building_type = row['btype'].upper()
    building_age = row['bage'].replace(" ","").upper
    code_end = '00'

    if "SINGLE" in building_type:
        building_type = "SFH"
    elif "MULTI" in building_type:
        building_type = "MFH"
    elif "APARTMENT" in building_type:
        building_type = "ABL"
    else:
        print("Building type not recognised.")

    if 'BEFORE' in building_age:
        building_age.replace("BEFORE", )

    building_code = country+building_type+building_age+code_end
    print(building_code)

UKSINGLE FAMILY- TERRACED HOUSESBefore194500
UKSINGLE FAMILY- TERRACED HOUSES1945-196900
UKSINGLE FAMILY- TERRACED HOUSES1970-197900
UKSINGLE FAMILY- TERRACED HOUSES1980-198900
UKSINGLE FAMILY- TERRACED HOUSES1990-199900
UKSINGLE FAMILY- TERRACED HOUSES2000-201000
UKSINGLE FAMILY- TERRACED HOUSESPost201000
UKMULTIFAMILY HOUSESBefore194500
UKMULTIFAMILY HOUSES1945-196900
UKMULTIFAMILY HOUSES1970-197900
UKMULTIFAMILY HOUSES1980-198900
UKMULTIFAMILY HOUSES1990-199900
UKMULTIFAMILY HOUSES2000-201000
UKMULTIFAMILY HOUSESPost201000
UKAPPARTMENT BLOCKSBefore194500
UKAPPARTMENT BLOCKS1945-196900
UKAPPARTMENT BLOCKS1970-197900
UKAPPARTMENT BLOCKS1980-198900
UKAPPARTMENT BLOCKS1990-199900
UKAPPARTMENT BLOCKS2000-201000
UKAPPARTMENT BLOCKSPost201000

In [ ]:
def create_ambience_building_code(hotmaps_data):
    for index, row in hotmaps_data.iterrows():
        country = row['country_code'].upper()
        building_type = row['btype']
        building_age = row['bage']
        code_end = '00'

        building_code = 

    AT-SFH-1981-1990-00
    
    country = hotmaps_data


    

    return hotmaps_data